### PR TITLE
Extend range of compatible Rake versions to include 13.x

### PR DESCRIPTION
**Pull request by nearapogee**
I want to use rake 13.x. So I bumped the compatible version, and all tests pass with rake 13.0.1.

Thank you for this gem!

### CODE REVIEW

**Comment by nearapogee** [comment]
@zenspider Anything I can do to help with this?

**Comment by zenspider** [comment]
Help me debug my github notifications? 😛

**Comment by zenspider** [comment]
Man.... I haven't had my coffee yet. I didn't even notice that this was a PR. I just bumped it to 15 because rake is moving too fast as a target. It's released. Sorry to not be terribly cogent.

**Comment by zenspider** [comment]
I saw that you forked vlad (wow?!?)... I assume you want to do the same thing there?

**Comment by nearapogee** [comment]
Yes please! Still a few applications using vlad/rake-remote_task.

I like simple.

**Pull request closed without merging**
